Updated workflow

diff --git a/.github/workflows/dev-workflow.yaml b/.github/workflows/dev-workflow.yaml
--- a/.github/workflows/dev-workflow.yaml
+++ b/.github/workflows/dev-workflow.yaml
@@ -7,7 +7,7 @@ on:
       - hotfix/*
 
 env:
-  HELM_REGISTRY: https://bin.cloud.barco.com/artifactory/helm-enp
+  HELM_REPO: https://bin.cloud.barco.com/artifactory/helm-enp
 
 jobs:
   setup-infra:
@@ -74,21 +74,85 @@ jobs:
           echo "Stashchart List"
           cat stashcharts.list
           echo
+        
+      - name: Upload Artifactory list
+        uses: actions/upload-artifact@v3
+        with:
+          name: output-artifactory-list
+          path: artifactory.list
 
-      # - name: Update Secrets in Helm values.yaml file
-      #   uses: microsoft/variable-substitution@v1 
-      #   with:
-      #     files: 'cheeseshop-chart/values.yaml'
-      #   env:
-      #     artifactoryAuth: ${{ secrets.ARTIFACTORY_AUTH }}
+      - name: Upload Stashcharts list
+        uses: actions/upload-artifact@v3
+        with:
+          name: output-stashcharts-list
+          path: stashcharts.list
 
-      # - name: Create Helm Package
-      #   shell: bash
-      #   run: |
-      #     find src/charts/ -type f -name 'Chart.yaml' | sed -r 's|/[^/]+$||' | sort | uniq | xargs -L 1 helm dep up
-      #     for d in src/charts/*/ ; do
-      #         echo "$d"
-      #         helm package "$d" -u -d dest
-      #     done
+  helm-package:
+    runs-on: ubuntu-latest
+    steps:
+      - name: Update Secrets in Helm values.yaml file
+        uses: microsoft/variable-substitution@v1 
+        with:
+          files: 'values.yaml'
+        env:
+          artifactoryAuth: ${{ secrets.ARTIFACTORY_AUTH }}
+
+      - name: Download Artifactory List
+        uses: actions/download-artifact@v3
+        with:
+          name: output-artifactory-list
+
+      - name: Download Stashcharts List
+        uses: actions/download-artifact@v3
+        with:
+          name: output-stashcharts-list
+
+      - name: Create Helm Packages
+        shell: bash
+        run: |
+          while read CHART;
+          do
+              GIT_CHART_NAME=`echo $CHART | cut -f 1 -d ":"`
+              GIT_CHART_VERSION=`echo $CHART | cut -f 2 -d ":"`
+              ART_CHART_NAME=$GIT_CHART_NAME
+              ART_CHART_VERSION=`grep "^${ART_CHART_NAME}:" artifactory.list | cut -f 2 -d ":" `
+
+              # if there is no chart in Artifactory, assume 0.0.0 version
+              if [ -z "$ART_CHART_VERSION" ]; then
+                  ART_CHART_VERSION="0.0.0"
+              fi
+
+              # Build dependencies first if needed
+              if [ -f $GIT_CHART_NAME/requirements.yaml ] || [ -f $GIT_CHART_NAME/Chart.lock ]; then
+                  helm dep build $GIT_CHART_NAME
+              fi
+
+              # Create helm package
+              helm package $GIT_CHART_NAME
+
+              # Upload to Artifactory
+              printf "\nUploading to Artifactory\n"
+
+              # (artifactory user is hardcoded intentionally)
+              curl --silent --show-error --fail -u ${ARTIFACTORYUSER} \
+                  -T "${GIT_CHART_NAME}-${GIT_CHART_VERSION}.tgz" \
+                  "${HELM_REPO}/${GIT_CHART_NAME}-${GIT_CHART_VERSION}.tgz"
+
+              res=$?
+
+              if test "$res" != "0"; then
+                  echo "the curl command failed with: $res"
+                  echo "New **Helm** chart CURL upload failed: **${GIT_CHART_NAME}:${GIT_CHART_VERSION}** reason: ${res}"
+                  exit 1
+              fi
+
+              echo "New **Helm** chart was released: **${GIT_CHART_NAME}:${GIT_CHART_VERSION}** & uploaded to Artifactory"
+
+              # Create a tag
+              # cd ../helm-enp-charts
+              pwd
+              git tag "${GIT_CHART_NAME}/${GIT_CHART_VERSION}" || true
+              cd -
+          done < stashcharts.list
 
     
